
function start() {
    document.write("Hello (Generated by start function)");

    const dateToday = new Date();
    document.getElementById("currentTime").innerHTML += dateToday;
}
start(); // To run at start

function change_sel() {
    var sel_id = getElementsByName('select1').selectedIndex;
    alert(getElementsByName('select1').options[sel_id].value);
}


